//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Microsoft.EntityFrameworkCore.Modeling
{
	internal static partial class Constants
	{
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
		public const string DesignerFileExtension = "efmd";
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
		public const string ProductName = @"Entity Framework Core Model Diagram";
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
		public const string CompanyName = @"Microsoft";
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
		public const string ProductVersion = "1.0.0.0";

		// Menu definitions
		public static readonly global::System.ComponentModel.Design.CommandID EntityFrameworkCoreDiagramMenu = new global::System.ComponentModel.Design.CommandID(new global::System.Guid(EntityFrameworkCoreCommandSetId), 0x10000);
		public static readonly global::System.ComponentModel.Design.CommandID EntityFrameworkCoreExplorerMenu = new global::System.ComponentModel.Design.CommandID(new global::System.Guid(EntityFrameworkCoreCommandSetId), 0x10001);

		// Command definitions
		public static readonly global::System.ComponentModel.Design.CommandID ViewEntityFrameworkCoreExplorerCommand = new global::System.ComponentModel.Design.CommandID(new global::System.Guid(EntityFrameworkCoreCommandSetId), 0x0001);
	
		// Package identifier
		public const string EntityFrameworkCorePackageId = "48725ce7-28dd-4de1-bd40-cfe6f4ab6a88";
		
		// Editor factory identifier
		public const string EntityFrameworkCoreEditorFactoryId = "6cf53e01-4ed1-4b31-baa6-6fcda0da4cf1";
		
		public const string DefaultDiagramExtension = ".diagram";
		
		// Model explorer tool window identifier
		public const string EntityFrameworkCoreModelExplorerToolWindowId = "5aebeaa7-25c6-4488-863a-04acf42d1072";
	}
}
//
// Constants not generated from values in DesignerDefinition.dsl are defined below
//
namespace Microsoft.EntityFrameworkCore.Modeling
{
	internal static partial class Constants
	{
		// Menu identifier
		public const string EntityFrameworkCoreCommandSetId = "17f792a7-8737-490e-bb01-5036b39c393c";
	}
}