//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Microsoft.EFDesigner
{
	internal static partial class Constants
	{
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
		public const string DesignerFileExtension = "ef";
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
		public const string ProductName = @"EFDesigner";
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
		public const string CompanyName = @"Microsoft";
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
		public const string ProductVersion = "1.0.0.0";

		// Menu definitions
		public static readonly global::System.ComponentModel.Design.CommandID EFDesignerDiagramMenu = new global::System.ComponentModel.Design.CommandID(new global::System.Guid(EFDesignerCommandSetId), 0x10000);
		public static readonly global::System.ComponentModel.Design.CommandID EFDesignerExplorerMenu = new global::System.ComponentModel.Design.CommandID(new global::System.Guid(EFDesignerCommandSetId), 0x10001);

		// Command definitions
		public static readonly global::System.ComponentModel.Design.CommandID ViewEFDesignerExplorerCommand = new global::System.ComponentModel.Design.CommandID(new global::System.Guid(EFDesignerCommandSetId), 0x0001);
	
		// Package identifier
		public const string EFDesignerPackageId = "48725ce7-28dd-4de1-bd40-cfe6f4ab6a88";
		
		// Editor factory identifier
		public const string EFDesignerEditorFactoryId = "b5fe0fb5-937c-4be0-a915-a1b803542241";
		
		public const string DefaultDiagramExtension = ".diagram";
		
		// Model explorer tool window identifier
		public const string EFDesignerModelExplorerToolWindowId = "3c9e489d-3cf3-4980-8cd0-0ffa8714a3de";
	}
}
//
// Constants not generated from values in DesignerDefinition.dsl are defined below
//
namespace Microsoft.EFDesigner
{
	internal static partial class Constants
	{
		// Menu identifier
		public const string EFDesignerCommandSetId = "371bd502-2827-4b8d-9535-d38b82b24a83";
	}
}